# Generated by Django 5.2.15 on 2026-06-05 04:28

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Documento',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Fecha de creación')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Fecha de actualización')),
                ('codigo', models.CharField(max_length=30, unique=True, verbose_name='Código')),
                ('titulo', models.CharField(max_length=255, verbose_name='Título')),
                ('tipo', models.CharField(choices=[('procedimiento', 'Procedimiento'), ('instructivo', 'Instructivo'), ('formato', 'Formato'), ('registro', 'Registro'), ('plan', 'Plan'), ('manual', 'Manual'), ('politica', 'Política')], max_length=20, verbose_name='Tipo')),
                ('proceso', models.CharField(blank=True, max_length=100, verbose_name='Proceso vinculado')),
                ('objetivo', models.TextField(blank=True, verbose_name='Objetivo')),
                ('alcance', models.TextField(blank=True, verbose_name='Alcance')),
                ('is_active', models.BooleanField(default=True, verbose_name='Activo')),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='%(class)s_creados', to=settings.AUTH_USER_MODEL, verbose_name='Creado por')),
                ('updated_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='%(class)s_actualizados', to=settings.AUTH_USER_MODEL, verbose_name='Actualizado por')),
            ],
            options={
                'verbose_name': 'Documento',
                'verbose_name_plural': 'Documentos',
                'ordering': ['codigo'],
            },
        ),
        migrations.CreateModel(
            name='VersionDocumento',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Fecha de creación')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Fecha de actualización')),
                ('version', models.CharField(max_length=10, verbose_name='Versión')),
                ('archivo', models.FileField(upload_to='documentos/%Y/', verbose_name='Archivo')),
                ('resumen_cambios', models.TextField(blank=True, verbose_name='Resumen de cambios')),
                ('estado', models.CharField(choices=[('borrador', 'Borrador'), ('en_revision', 'En revisión'), ('en_aprobacion', 'En aprobación'), ('vigente', 'Vigente'), ('obsoleto', 'Obsoleto'), ('rechazado', 'Rechazado')], default='borrador', max_length=20, verbose_name='Estado')),
                ('comentarios_revision', models.TextField(blank=True, verbose_name='Comentarios de revisión')),
                ('fecha_revision', models.DateTimeField(blank=True, null=True, verbose_name='Fecha de revisión')),
                ('fecha_aprobacion', models.DateTimeField(blank=True, null=True, verbose_name='Fecha de aprobación')),
                ('fecha_vigencia', models.DateField(blank=True, null=True, verbose_name='Vigente desde')),
                ('fecha_proxima_revision', models.DateField(blank=True, null=True, verbose_name='Próxima revisión')),
                ('aprobado_por', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='versiones_aprobadas', to=settings.AUTH_USER_MODEL, verbose_name='Aprobado por')),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='%(class)s_creados', to=settings.AUTH_USER_MODEL, verbose_name='Creado por')),
                ('documento', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='versiones', to='esynapse_sig.documento', verbose_name='Documento')),
                ('elaborado_por', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='versiones_elaboradas', to=settings.AUTH_USER_MODEL, verbose_name='Elaborado por')),
                ('revisado_por', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='versiones_revisadas', to=settings.AUTH_USER_MODEL, verbose_name='Revisado por')),
                ('updated_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='%(class)s_actualizados', to=settings.AUTH_USER_MODEL, verbose_name='Actualizado por')),
            ],
            options={
                'verbose_name': 'Versión de documento',
                'verbose_name_plural': 'Versiones de documentos',
                'ordering': ['-id'],
                'constraints': [models.UniqueConstraint(fields=('documento', 'version'), name='unique_documento_version')],
            },
        ),
    ]
