# Generated by Django 5.2.15 on 2026-06-05 04:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('esynapse_sig', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='versiondocumento',
            name='estado',
            field=models.CharField(choices=[('borrador', 'En elaboración'), ('en_revision', 'En revisión'), ('en_aprobacion', 'En aprobación'), ('vigente', 'Vigente'), ('obsoleto', 'Obsoleto'), ('rechazado', 'Rechazado')], default='borrador', max_length=20, verbose_name='Estado'),
        ),
    ]
