# Generated by Django 5.2.15 on 2026-06-05 04:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('esynapse_sig', '0002_alter_versiondocumento_estado'),
    ]

    operations = [
        migrations.AddField(
            model_name='documento',
            name='meses_revision',
            field=models.PositiveSmallIntegerField(default=12, help_text='Cada cuántos meses debe revisarse el documento una vez vigente', verbose_name='Frecuencia de revisión (meses)'),
        ),
    ]
