# Generated by Django 5.2.15 on 2026-06-05 05:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('esynapse_sig', '0003_documento_meses_revision'),
    ]

    operations = [
        migrations.AddField(
            model_name='documento',
            name='normas_aplicables',
            field=models.JSONField(blank=True, default=list, help_text='Lista de claves de NORMAS_APLICABLES (ej: ["iso_9001", "iso_17025"])', verbose_name='Normas aplicables'),
        ),
        migrations.AddField(
            model_name='documento',
            name='soporte',
            field=models.CharField(choices=[('digital', 'Digital'), ('fisico', 'Físico')], default='digital', max_length=10, verbose_name='Soporte'),
        ),
    ]
