# Generated by Django 5.2.15 on 2026-06-05 05:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('esynapse_sig', '0004_documento_normas_aplicables_documento_soporte'),
    ]

    operations = [
        migrations.AddField(
            model_name='documento',
            name='anos_retencion',
            field=models.PositiveSmallIntegerField(default=5, help_text='Años que el documento y sus registros deben conservarse', verbose_name='Tiempo de retención (años)'),
        ),
    ]
