# Generated by Django 5.2.15 on 2026-06-05 05:47

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('esynapse_sig', '0005_documento_anos_retencion'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='documento',
            name='dias_verificacion',
            field=models.PositiveSmallIntegerField(default=7, help_text='Cada cuántos días debe verificarse la vigencia del documento externo', verbose_name='Frecuencia de verificación (días)'),
        ),
        migrations.AddField(
            model_name='documento',
            name='entidad_emisora',
            field=models.CharField(blank=True, help_text='INACAL-DA, ISO, MINTRA, fabricante, etc. Solo para documentos externos.', max_length=150, verbose_name='Entidad emisora'),
        ),
        migrations.AddField(
            model_name='documento',
            name='origen',
            field=models.CharField(choices=[('interno', 'Interno'), ('externo', 'Externo')], default='interno', max_length=10, verbose_name='Origen'),
        ),
        migrations.AddField(
            model_name='documento',
            name='ultima_verificacion',
            field=models.DateTimeField(blank=True, null=True, verbose_name='Última verificación'),
        ),
        migrations.AlterField(
            model_name='documento',
            name='tipo',
            field=models.CharField(choices=[('politica', 'Política'), ('manual', 'Manual'), ('reglamento', 'Reglamento'), ('plan', 'Plan'), ('programa', 'Programa'), ('procedimiento', 'Procedimiento'), ('formato', 'Formato'), ('pets', 'PETS'), ('instructivo', 'Instructivo'), ('registro', 'Registro')], max_length=20, verbose_name='Tipo'),
        ),
        migrations.CreateModel(
            name='VerificacionExterna',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Fecha de creación')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Fecha de actualización')),
                ('vigente', models.BooleanField(default=True, verbose_name='Sigue vigente')),
                ('observaciones', models.TextField(blank=True, verbose_name='Observaciones')),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='%(class)s_creados', to=settings.AUTH_USER_MODEL, verbose_name='Creado por')),
                ('documento', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='verificaciones', to='esynapse_sig.documento', verbose_name='Documento')),
                ('updated_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='%(class)s_actualizados', to=settings.AUTH_USER_MODEL, verbose_name='Actualizado por')),
            ],
            options={
                'verbose_name': 'Verificación de documento externo',
                'verbose_name_plural': 'Verificaciones de documentos externos',
                'ordering': ['-created_at'],
            },
        ),
    ]
