# Generated by Django 5.2.15 on 2026-06-05 06:13

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('esynapse_sig', '0006_documento_dias_verificacion_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Hallazgo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Fecha de creación')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Fecha de actualización')),
                ('codigo', models.CharField(editable=False, max_length=20, unique=True, verbose_name='Código')),
                ('tipo', models.CharField(choices=[('nc_mayor', 'NC Mayor'), ('nc_menor', 'NC Menor'), ('observacion', 'Observación'), ('odm', 'Oportunidad de Mejora')], max_length=20, verbose_name='Tipo')),
                ('fuente', models.CharField(choices=[('auditoria_interna', 'Auditoría interna'), ('auditoria_externa', 'Auditoría externa'), ('inspeccion', 'Inspección'), ('queja', 'Queja'), ('seguimiento', 'Seguimiento de procesos'), ('indicador', 'Indicador'), ('riesgo', 'Riesgo materializado'), ('otro', 'Otro')], max_length=30, verbose_name='Fuente')),
                ('proceso', models.CharField(max_length=100, verbose_name='Proceso afectado')),
                ('descripcion', models.TextField(verbose_name='Descripción del hallazgo')),
                ('requisito', models.CharField(blank=True, help_text='Cláusula de norma o requisito legal (ej: ISO 17025 7.8.2)', max_length=200, verbose_name='Requisito incumplido')),
                ('lugar', models.CharField(blank=True, max_length=150, verbose_name='Lugar de detección')),
                ('fecha_deteccion', models.DateField(verbose_name='Fecha de detección')),
                ('evidencia', models.FileField(blank=True, null=True, upload_to='hallazgos/%Y/', verbose_name='Evidencia')),
                ('estado', models.CharField(choices=[('registrado', 'Registrado'), ('en_analisis', 'En análisis'), ('en_tratamiento', 'En tratamiento'), ('cerrado', 'Cerrado'), ('reabierto', 'Reabierto')], default='registrado', max_length=20, verbose_name='Estado')),
                ('analisis', models.TextField(blank=True, verbose_name='Análisis del hallazgo')),
                ('correccion', models.TextField(blank=True, verbose_name='Corrección inmediata aplicada')),
                ('comentarios_cierre', models.TextField(blank=True, verbose_name='Comentarios de cierre')),
                ('fecha_cierre', models.DateTimeField(blank=True, null=True, verbose_name='Fecha de cierre')),
                ('requiere_ac', models.BooleanField(default=False, help_text='Las NC Mayores la requieren automáticamente (se vincula en M9)', verbose_name='Requiere acción correctiva')),
                ('is_active', models.BooleanField(default=True, verbose_name='Activo')),
                ('cerrado_por', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='hallazgos_cerrados', to=settings.AUTH_USER_MODEL, verbose_name='Cerrado por')),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='%(class)s_creados', to=settings.AUTH_USER_MODEL, verbose_name='Creado por')),
                ('responsable', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='hallazgos_asignados', to=settings.AUTH_USER_MODEL, verbose_name='Responsable del tratamiento')),
                ('updated_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='%(class)s_actualizados', to=settings.AUTH_USER_MODEL, verbose_name='Actualizado por')),
            ],
            options={
                'verbose_name': 'Hallazgo',
                'verbose_name_plural': 'Hallazgos',
                'ordering': ['-id'],
            },
        ),
    ]
