# Generated by Django 5.2.15 on 2026-06-05 06:32

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('esynapse_sig', '0007_hallazgo'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='versiondocumento',
            name='archivo_publicado',
            field=models.FileField(blank=True, null=True, upload_to='documentos/publicados/%Y/', verbose_name='PDF firmado (copia controlada)'),
        ),
        migrations.AddField(
            model_name='versiondocumento',
            name='hash_publicado',
            field=models.CharField(blank=True, max_length=64, verbose_name='SHA-256 del PDF publicado'),
        ),
        migrations.CreateModel(
            name='FirmaVersion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Fecha de creación')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Fecha de actualización')),
                ('rol', models.CharField(choices=[('elaborado', 'Elaborado'), ('revisado', 'Revisado'), ('aprobado', 'Aprobado')], max_length=15, verbose_name='Rol de firma')),
                ('cargo', models.CharField(blank=True, max_length=100, verbose_name='Cargo al firmar')),
                ('ip', models.GenericIPAddressField(blank=True, null=True, verbose_name='IP')),
                ('hash_archivo', models.CharField(max_length=64, verbose_name='SHA-256 del archivo firmado')),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='%(class)s_creados', to=settings.AUTH_USER_MODEL, verbose_name='Creado por')),
                ('updated_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='%(class)s_actualizados', to=settings.AUTH_USER_MODEL, verbose_name='Actualizado por')),
                ('usuario', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='firmas_documentos', to=settings.AUTH_USER_MODEL, verbose_name='Firmante')),
                ('version', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='firmas', to='esynapse_sig.versiondocumento', verbose_name='Versión')),
            ],
            options={
                'verbose_name': 'Firma electrónica',
                'verbose_name_plural': 'Firmas electrónicas',
                'ordering': ['id'],
                'constraints': [models.UniqueConstraint(fields=('version', 'rol'), name='unique_firma_version_rol')],
            },
        ),
    ]
