# Generated by Django 5.2.15 on 2026-06-05 17:12

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('esynapse_sig', '0008_versiondocumento_archivo_publicado_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='ObservacionVersion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Fecha de creación')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Fecha de actualización')),
                ('etapa', models.CharField(choices=[('revision', 'Revisión'), ('aprobacion', 'Aprobación')], max_length=15, verbose_name='Etapa')),
                ('accion', models.CharField(choices=[('devuelto', 'Devuelto a elaboración'), ('rechazado', 'Rechazado definitivamente')], max_length=15, verbose_name='Acción')),
                ('comentarios', models.TextField(verbose_name='Comentarios')),
                ('archivo', models.FileField(blank=True, null=True, upload_to='documentos/observaciones/%Y/', verbose_name='Archivo con anotaciones')),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='%(class)s_creados', to=settings.AUTH_USER_MODEL, verbose_name='Creado por')),
                ('updated_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='%(class)s_actualizados', to=settings.AUTH_USER_MODEL, verbose_name='Actualizado por')),
                ('version', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='observaciones', to='esynapse_sig.versiondocumento', verbose_name='Versión')),
            ],
            options={
                'verbose_name': 'Observación de versión',
                'verbose_name_plural': 'Observaciones de versiones',
                'ordering': ['-id'],
            },
        ),
    ]
