# Generated by Django 5.2.15 on 2026-06-05 17:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('esynapse_sig', '0009_observacionversion'),
    ]

    operations = [
        migrations.AddField(
            model_name='documento',
            name='archivado',
            field=models.BooleanField(default=False, help_text='Retirado del uso activo; se conserva durante su periodo de retención (SIG-PRO-01 6.6)', verbose_name='Archivado'),
        ),
        migrations.AddField(
            model_name='documento',
            name='fecha_archivado',
            field=models.DateTimeField(blank=True, null=True, verbose_name='Fecha de archivado'),
        ),
    ]
