# Generated by Django 5.2.15 on 2026-06-05 21:57

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('esynapse_sig', '0010_documento_archivado_documento_fecha_archivado'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='SolicitudAC',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Fecha de creación')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Fecha de actualización')),
                ('codigo', models.CharField(editable=False, max_length=20, unique=True, verbose_name='Código')),
                ('fuente', models.CharField(choices=[('auditoria_interna', 'Auditoría interna'), ('auditoria_externa', 'Auditoría externa'), ('revision_direccion', 'Revisión por la Dirección'), ('queja', 'Queja'), ('otros', 'Otros')], max_length=30, verbose_name='Procedencia')),
                ('fuente_detalle', models.CharField(blank=True, max_length=200, verbose_name='Detalle de procedencia')),
                ('normas_aplicables', models.JSONField(blank=True, default=list, verbose_name='Normas aplicables')),
                ('auditor', models.CharField(blank=True, max_length=150, verbose_name='Auditor')),
                ('auditado', models.CharField(blank=True, max_length=150, verbose_name='Auditado')),
                ('requisito_auditado', models.CharField(blank=True, max_length=200, verbose_name='Requisito auditado')),
                ('descripcion_nc', models.TextField(verbose_name='Descripción de la No Conformidad')),
                ('significancia', models.CharField(blank=True, choices=[('bajo', 'Bajo'), ('alto', 'Alto')], max_length=10, verbose_name='Nivel de significancia')),
                ('analisis_extension', models.TextField(blank=True, verbose_name='Análisis de la extensión')),
                ('requiere_ac', models.BooleanField(blank=True, null=True, verbose_name='Requiere acción correctiva')),
                ('justificacion_evaluacion', models.TextField(blank=True, verbose_name='Justificación de la evaluación')),
                ('porques', models.JSONField(blank=True, default=list, verbose_name='5 Porqués')),
                ('causa_raiz', models.TextField(blank=True, verbose_name='Causa raíz')),
                ('aplica_cambios_sig', models.BooleanField(blank=True, null=True, verbose_name='¿Aplica cambios al SIG?')),
                ('aplica_actualizar_riesgos', models.BooleanField(blank=True, null=True, verbose_name='¿Aplica actualizar matriz de riesgos?')),
                ('estado', models.CharField(choices=[('registrada', 'Registrada'), ('en_analisis', 'En análisis de causa'), ('en_implementacion', 'En implementación'), ('en_verificacion', 'En verificación de eficacia'), ('cerrada_conforme', 'Cerrada conforme'), ('cerrada_sin_ac', 'Cerrada (solo corrección)')], default='registrada', max_length=25, verbose_name='Estado')),
                ('evaluacion_eficacia', models.TextField(blank=True, verbose_name='Evaluación de la eficacia')),
                ('resultado_eficaz', models.BooleanField(blank=True, null=True, verbose_name='Resultado eficaz')),
                ('fecha_verificacion', models.DateTimeField(blank=True, null=True, verbose_name='Fecha de verificación')),
                ('fecha_cierre', models.DateTimeField(blank=True, null=True, verbose_name='Fecha de cierre')),
                ('is_active', models.BooleanField(default=True, verbose_name='Activo')),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='%(class)s_creados', to=settings.AUTH_USER_MODEL, verbose_name='Creado por')),
                ('hallazgo', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='solicitudes_ac', to='esynapse_sig.hallazgo', verbose_name='Hallazgo vinculado (M8)')),
                ('responsable', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='sac_asignadas', to=settings.AUTH_USER_MODEL, verbose_name='Responsable del tratamiento')),
                ('updated_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='%(class)s_actualizados', to=settings.AUTH_USER_MODEL, verbose_name='Actualizado por')),
                ('verificador', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='sac_a_verificar', to=settings.AUTH_USER_MODEL, verbose_name='Verificador de eficacia')),
            ],
            options={
                'verbose_name': 'Solicitud de Acción Correctiva',
                'verbose_name_plural': 'Solicitudes de Acción Correctiva',
                'ordering': ['-id'],
            },
        ),
        migrations.CreateModel(
            name='AccionSAC',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Fecha de creación')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Fecha de actualización')),
                ('tipo', models.CharField(choices=[('correccion', 'Corrección'), ('correctiva', 'Acción correctiva')], max_length=15, verbose_name='Tipo')),
                ('descripcion', models.TextField(verbose_name='Descripción de la acción')),
                ('fecha_propuesta', models.DateField(verbose_name='Fecha propuesta')),
                ('estado', models.CharField(choices=[('pendiente', 'Pendiente'), ('completada', 'Completada')], default='pendiente', max_length=15, verbose_name='Estado')),
                ('fecha_completada', models.DateField(blank=True, null=True, verbose_name='Fecha de ejecución')),
                ('verificacion', models.TextField(blank=True, verbose_name='Verificación de la acción')),
                ('evidencia', models.FileField(blank=True, null=True, upload_to='sac/evidencias/%Y/', verbose_name='Evidencia')),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='%(class)s_creados', to=settings.AUTH_USER_MODEL, verbose_name='Creado por')),
                ('responsable', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='acciones_sac', to=settings.AUTH_USER_MODEL, verbose_name='Responsable')),
                ('updated_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='%(class)s_actualizados', to=settings.AUTH_USER_MODEL, verbose_name='Actualizado por')),
                ('solicitud', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='acciones', to='esynapse_sig.solicitudac', verbose_name='Solicitud')),
            ],
            options={
                'verbose_name': 'Acción de SAC',
                'verbose_name_plural': 'Acciones de SAC',
                'ordering': ['fecha_propuesta', 'id'],
            },
        ),
    ]
