# Generated by Django 5.2.15 on 2026-06-06 02:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('esynapse_sig', '0011_solicitudac_accionsac'),
    ]

    operations = [
        migrations.AddField(
            model_name='observacionversion',
            name='resuelta',
            field=models.BooleanField(default=False, verbose_name='Resuelta'),
        ),
    ]
