# Generated by Django 5.2.15 on 2026-06-06 03:35

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('esynapse_sig', '0012_observacionversion_resuelta'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='versiondocumento',
            name='requiere_recarga',
            field=models.BooleanField(default=False, verbose_name='Requiere recarga del corregido'),
        ),
        migrations.CreateModel(
            name='ArchivoVersion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Fecha de creación')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Fecha de actualización')),
                ('archivo', models.FileField(upload_to='documentos/historial/%Y/', verbose_name='Archivo')),
                ('origen', models.CharField(choices=[('elaboracion', 'Cargado en elaboración'), ('correccion', 'Corrección del elaborador'), ('anotado_revision', 'Anotado por el revisor'), ('anotado_aprobacion', 'Anotado por el aprobador'), ('nueva_version', 'Nueva versión')], max_length=20, verbose_name='Origen')),
                ('etapa', models.CharField(blank=True, max_length=20, verbose_name='Etapa al registrar')),
                ('hash_archivo', models.CharField(blank=True, max_length=64, verbose_name='SHA-256')),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='%(class)s_creados', to=settings.AUTH_USER_MODEL, verbose_name='Creado por')),
                ('updated_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='%(class)s_actualizados', to=settings.AUTH_USER_MODEL, verbose_name='Actualizado por')),
                ('version', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='historial_archivos', to='esynapse_sig.versiondocumento', verbose_name='Versión')),
            ],
            options={
                'verbose_name': 'Archivo de versión (bitácora)',
                'verbose_name_plural': 'Bitácora de archivos de versiones',
                'ordering': ['-id'],
            },
        ),
    ]
