# Generated by Django 5.2.15 on 2026-06-06 04:19

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('esynapse_sig', '0013_versiondocumento_requiere_recarga_archivoversion'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Auditoria',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Fecha de creación')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Fecha de actualización')),
                ('codigo', models.CharField(editable=False, max_length=20, unique=True, verbose_name='Código')),
                ('tipo', models.CharField(choices=[('programada', 'Programada'), ('extraordinaria', 'Extraordinaria')], default='programada', max_length=15, verbose_name='Tipo')),
                ('normas_aplicables', models.JSONField(blank=True, default=list, verbose_name='Normas / criterios')),
                ('objetivo', models.TextField(blank=True, verbose_name='Objetivo')),
                ('alcance', models.TextField(blank=True, verbose_name='Alcance')),
                ('criterios', models.TextField(blank=True, verbose_name='Criterios de auditoría')),
                ('documentos_referencia', models.TextField(blank=True, verbose_name='Documentos de referencia')),
                ('areas_procesos', models.TextField(blank=True, verbose_name='Áreas / procesos a auditar')),
                ('modalidad', models.CharField(choices=[('presencial', 'Presencial (in situ)'), ('remota', 'Remota'), ('hibrido', 'Híbrido')], default='presencial', max_length=12, verbose_name='Modalidad')),
                ('mes_programado', models.PositiveSmallIntegerField(blank=True, null=True, verbose_name='Mes programado')),
                ('fecha_programada', models.DateField(blank=True, null=True, verbose_name='Fecha programada')),
                ('fecha_inicio', models.DateField(blank=True, null=True, verbose_name='Inicio')),
                ('fecha_fin', models.DateField(blank=True, null=True, verbose_name='Fin')),
                ('reprogramada', models.BooleanField(default=False, verbose_name='Reprogramada')),
                ('motivo_reprogramacion', models.CharField(blank=True, max_length=255, verbose_name='Motivo de reprogramación')),
                ('estado', models.CharField(choices=[('programada', 'Programada'), ('planificada', 'Planificada'), ('en_ejecucion', 'En ejecución'), ('en_informe', 'En informe'), ('cerrada', 'Cerrada')], default='programada', max_length=15, verbose_name='Estado')),
                ('fortalezas', models.TextField(blank=True, verbose_name='Fortalezas')),
                ('debilidades', models.TextField(blank=True, verbose_name='Debilidades')),
                ('conclusiones', models.TextField(blank=True, verbose_name='Conclusiones')),
                ('fecha_informe', models.DateTimeField(blank=True, null=True, verbose_name='Fecha de informe')),
                ('is_active', models.BooleanField(default=True, verbose_name='Activo')),
                ('auditor_lider', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='auditorias_lideradas', to=settings.AUTH_USER_MODEL)),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='%(class)s_creados', to=settings.AUTH_USER_MODEL, verbose_name='Creado por')),
                ('updated_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='%(class)s_actualizados', to=settings.AUTH_USER_MODEL, verbose_name='Actualizado por')),
            ],
            options={
                'verbose_name': 'Auditoría interna',
                'verbose_name_plural': 'Auditorías internas',
                'ordering': ['-id'],
            },
        ),
        migrations.AddField(
            model_name='hallazgo',
            name='auditoria',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='hallazgos', to='esynapse_sig.auditoria', verbose_name='Auditoría de origen'),
        ),
        migrations.CreateModel(
            name='EquipoAuditoria',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Fecha de creación')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Fecha de actualización')),
                ('nombre_externo', models.CharField(blank=True, max_length=150, verbose_name='Nombre (externo)')),
                ('rol', models.CharField(choices=[('lider', 'Auditor líder'), ('auditor', 'Auditor'), ('experto', 'Experto técnico'), ('observador', 'Observador')], max_length=12, verbose_name='Rol')),
                ('cargo', models.CharField(blank=True, max_length=120, verbose_name='Cargo')),
                ('auditoria', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='equipo', to='esynapse_sig.auditoria')),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='%(class)s_creados', to=settings.AUTH_USER_MODEL, verbose_name='Creado por')),
                ('updated_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='%(class)s_actualizados', to=settings.AUTH_USER_MODEL, verbose_name='Actualizado por')),
                ('usuario', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='participaciones_auditoria', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Integrante del equipo auditor',
                'verbose_name_plural': 'Equipo auditor',
                'ordering': ['id'],
            },
        ),
        migrations.CreateModel(
            name='ListaVerificacion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Fecha de creación')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Fecha de actualización')),
                ('norma', models.CharField(choices=[('iso_9001', 'ISO 9001'), ('iso_14001', 'ISO 14001'), ('iso_45001', 'ISO 45001 / Ley 29783'), ('iso_17025', 'NTP ISO/IEC 17025')], max_length=20, verbose_name='Norma')),
                ('auditoria', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='listas', to='esynapse_sig.auditoria')),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='%(class)s_creados', to=settings.AUTH_USER_MODEL, verbose_name='Creado por')),
                ('updated_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='%(class)s_actualizados', to=settings.AUTH_USER_MODEL, verbose_name='Actualizado por')),
            ],
            options={
                'verbose_name': 'Lista de verificación',
                'verbose_name_plural': 'Listas de verificación',
                'ordering': ['id'],
            },
        ),
        migrations.CreateModel(
            name='ItemVerificacion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Fecha de creación')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Fecha de actualización')),
                ('codigo', models.CharField(max_length=15, verbose_name='Cláusula')),
                ('titulo', models.CharField(max_length=255, verbose_name='Requisito')),
                ('es_seccion', models.BooleanField(default=False, verbose_name='Es sección')),
                ('orden', models.PositiveIntegerField(default=0, verbose_name='Orden')),
                ('resultado', models.CharField(choices=[('pendiente', 'Pendiente'), ('cumple', 'Cumple'), ('no_cumple', 'No cumple'), ('na', 'No aplica'), ('observa', 'Observación')], default='pendiente', max_length=12, verbose_name='Resultado')),
                ('evidencia', models.TextField(blank=True, verbose_name='Evidencia')),
                ('observacion', models.TextField(blank=True, verbose_name='Observación')),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='%(class)s_creados', to=settings.AUTH_USER_MODEL, verbose_name='Creado por')),
                ('updated_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='%(class)s_actualizados', to=settings.AUTH_USER_MODEL, verbose_name='Actualizado por')),
                ('lista', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='items', to='esynapse_sig.listaverificacion')),
            ],
            options={
                'verbose_name': 'Ítem de verificación',
                'verbose_name_plural': 'Ítems de verificación',
                'ordering': ['lista', 'orden'],
            },
        ),
        migrations.CreateModel(
            name='ProgramaAuditoria',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Fecha de creación')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Fecha de actualización')),
                ('anio', models.PositiveIntegerField(unique=True, verbose_name='Año')),
                ('estado', models.CharField(choices=[('borrador', 'Borrador'), ('aprobado', 'Aprobado')], default='borrador', max_length=15, verbose_name='Estado')),
                ('fecha_aprobacion', models.DateTimeField(blank=True, null=True, verbose_name='Fecha de aprobación')),
                ('observaciones', models.TextField(blank=True, verbose_name='Observaciones')),
                ('is_active', models.BooleanField(default=True, verbose_name='Activo')),
                ('aprobado_por', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='programas_aprobados', to=settings.AUTH_USER_MODEL)),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='%(class)s_creados', to=settings.AUTH_USER_MODEL, verbose_name='Creado por')),
                ('updated_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='%(class)s_actualizados', to=settings.AUTH_USER_MODEL, verbose_name='Actualizado por')),
            ],
            options={
                'verbose_name': 'Programa anual de auditorías',
                'verbose_name_plural': 'Programas anuales de auditorías',
                'ordering': ['-anio'],
            },
        ),
        migrations.AddField(
            model_name='auditoria',
            name='programa',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='auditorias', to='esynapse_sig.programaauditoria'),
        ),
        migrations.CreateModel(
            name='RequisitoNorma',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('norma', models.CharField(choices=[('iso_9001', 'ISO 9001'), ('iso_14001', 'ISO 14001'), ('iso_45001', 'ISO 45001 / Ley 29783'), ('iso_17025', 'NTP ISO/IEC 17025')], max_length=20, verbose_name='Norma')),
                ('codigo', models.CharField(max_length=15, verbose_name='Cláusula')),
                ('titulo', models.CharField(max_length=255, verbose_name='Título')),
                ('es_seccion', models.BooleanField(default=False, verbose_name='Es sección')),
                ('orden', models.PositiveIntegerField(default=0, verbose_name='Orden')),
            ],
            options={
                'verbose_name': 'Requisito de norma',
                'verbose_name_plural': 'Catálogo de requisitos de normas',
                'ordering': ['norma', 'orden'],
                'constraints': [models.UniqueConstraint(fields=('norma', 'codigo'), name='unique_norma_codigo')],
            },
        ),
        migrations.CreateModel(
            name='ActaAuditoria',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Fecha de creación')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Fecha de actualización')),
                ('tipo', models.CharField(choices=[('apertura', 'Apertura'), ('cierre', 'Cierre')], max_length=10, verbose_name='Tipo')),
                ('participantes', models.JSONField(blank=True, default=list, verbose_name='Participantes')),
                ('contenido', models.TextField(blank=True, verbose_name='Contenido')),
                ('observaciones_auditado', models.TextField(blank=True, verbose_name='Observaciones del área auditada')),
                ('archivo', models.FileField(blank=True, null=True, upload_to='auditorias/actas/%Y/', verbose_name='Acta firmada')),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='%(class)s_creados', to=settings.AUTH_USER_MODEL, verbose_name='Creado por')),
                ('updated_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='%(class)s_actualizados', to=settings.AUTH_USER_MODEL, verbose_name='Actualizado por')),
                ('auditoria', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='actas', to='esynapse_sig.auditoria')),
            ],
            options={
                'verbose_name': 'Acta de auditoría',
                'verbose_name_plural': 'Actas de auditoría',
                'ordering': ['id'],
                'constraints': [models.UniqueConstraint(fields=('auditoria', 'tipo'), name='unique_acta_tipo')],
            },
        ),
        migrations.AddConstraint(
            model_name='listaverificacion',
            constraint=models.UniqueConstraint(fields=('auditoria', 'norma'), name='unique_lista_norma'),
        ),
    ]
