# Generated by Django 5.2.15 on 2026-06-24 21:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('esynapse_sig', '0016_cartatrazabilidad_equipo_actividadprograma_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='documento',
            name='archivado',
            field=models.BooleanField(default=False, help_text='Retirado del uso activo; se conserva durante su periodo de retención', verbose_name='Archivado'),
        ),
    ]
