# Generated by Django 5.2.15 on 2026-06-24 22:35

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('esynapse_sig', '0017_alter_documento_archivado'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='equipo',
            name='resolucion',
            field=models.CharField(blank=True, max_length=80, verbose_name='Resolución'),
        ),
        migrations.AlterField(
            model_name='equipo',
            name='cantidad',
            field=models.CharField(blank=True, max_length=40, verbose_name='Alcance / Cantidad'),
        ),
        migrations.AlterField(
            model_name='equipo',
            name='codigo',
            field=models.CharField(help_text='Lo asigna el laboratorio (p. ej. M-001, TH-01).', max_length=20, unique=True, verbose_name='Código'),
        ),
        migrations.CreateModel(
            name='RegistroEquipo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Fecha de creación')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Fecha de actualización')),
                ('tipo', models.CharField(choices=[('calibracion', 'Calibración'), ('mantenimiento', 'Mantenimiento'), ('verificacion', 'Verificación'), ('comprobacion_intermedia', 'Comprobación Intermedia'), ('caracterizacion', 'Caracterización'), ('suceso', 'Historial de Sucesos')], max_length=25, verbose_name='Tipo de registro')),
                ('frecuencia', models.CharField(blank=True, max_length=80, verbose_name='Frecuencia')),
                ('numero_documento', models.CharField(blank=True, max_length=120, verbose_name='N° de certificado / informe')),
                ('descripcion', models.TextField(blank=True, verbose_name='Sucesos / detalle')),
                ('fecha', models.DateField(blank=True, null=True, verbose_name='Fecha')),
                ('fecha_proxima', models.DateField(blank=True, null=True, verbose_name='Próxima fecha / fecha de solución')),
                ('observaciones', models.TextField(blank=True, verbose_name='Observaciones')),
                ('vb', models.CharField(blank=True, max_length=150, verbose_name='V°B° (responsable)')),
                ('archivo', models.FileField(blank=True, null=True, upload_to='equipos/registros/%Y/', verbose_name='Documento adjunto')),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='%(class)s_creados', to=settings.AUTH_USER_MODEL, verbose_name='Creado por')),
                ('equipo', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='registros', to='esynapse_sig.equipo')),
                ('updated_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='%(class)s_actualizados', to=settings.AUTH_USER_MODEL, verbose_name='Actualizado por')),
            ],
            options={
                'verbose_name': 'Registro de hoja de vida',
                'verbose_name_plural': 'Registros de hoja de vida',
                'ordering': ['-fecha', '-id'],
            },
        ),
    ]
