# Generated by Django 5.2.15 on 2026-06-24 23:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('esynapse_sig', '0019_rename_periodicidad_dias'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='cartatrazabilidad',
            options={'verbose_name': 'Carta de trazabilidad'},
        ),
        migrations.AddField(
            model_name='equipo',
            name='observaciones',
            field=models.TextField(blank=True, verbose_name='Observaciones'),
        ),
        migrations.AddField(
            model_name='equipo',
            name='proveedor_calibracion',
            field=models.CharField(blank=True, max_length=150, verbose_name='Proveedor de calibración'),
        ),
    ]
