# Generated by Django 5.2.15 on 2026-06-24 23:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('esynapse_sig', '0020_alter_cartatrazabilidad_options_equipo_observaciones_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='cartatrazabilidad',
            options={'ordering': ['magnitud'], 'verbose_name': 'Carta de trazabilidad', 'verbose_name_plural': 'Cartas de trazabilidad'},
        ),
        migrations.AddField(
            model_name='equipo',
            name='imagen',
            field=models.FileField(blank=True, null=True, upload_to='equipos/imagenes/%Y/', verbose_name='Imagen del equipo'),
        ),
    ]
