# Generated by Django 5.2.15 on 2026-06-25 04:48

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('esynapse_sig', '0021_alter_cartatrazabilidad_options_equipo_imagen'),
    ]

    operations = [
        migrations.AddField(
            model_name='documento',
            name='padre',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='hijos', to='esynapse_sig.documento', verbose_name='Documento padre'),
        ),
    ]
