# Generated by Django 5.2.15 on 2026-06-05 02:43

import django.contrib.auth.models
import django.contrib.auth.validators
import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('auth', '0012_alter_user_first_name_max_length'),
    ]

    operations = [
        migrations.CreateModel(
            name='Usuario',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('password', models.CharField(max_length=128, verbose_name='password')),
                ('last_login', models.DateTimeField(blank=True, null=True, verbose_name='last login')),
                ('is_superuser', models.BooleanField(default=False, help_text='Designates that this user has all permissions without explicitly assigning them.', verbose_name='superuser status')),
                ('username', models.CharField(error_messages={'unique': 'A user with that username already exists.'}, help_text='Required. 150 characters or fewer. Letters, digits and @/./+/-/_ only.', max_length=150, unique=True, validators=[django.contrib.auth.validators.UnicodeUsernameValidator()], verbose_name='username')),
                ('first_name', models.CharField(blank=True, max_length=150, verbose_name='first name')),
                ('last_name', models.CharField(blank=True, max_length=150, verbose_name='last name')),
                ('is_staff', models.BooleanField(default=False, help_text='Designates whether the user can log into this admin site.', verbose_name='staff status')),
                ('is_active', models.BooleanField(default=True, help_text='Designates whether this user should be treated as active. Unselect this instead of deleting accounts.', verbose_name='active')),
                ('date_joined', models.DateTimeField(default=django.utils.timezone.now, verbose_name='date joined')),
                ('email', models.EmailField(max_length=254, unique=True, verbose_name='Correo electrónico')),
                ('area', models.CharField(max_length=100, verbose_name='Área')),
                ('laboratorio', models.CharField(blank=True, max_length=100, verbose_name='Laboratorio')),
                ('cargo', models.CharField(max_length=100, verbose_name='Cargo')),
                ('telefono', models.CharField(blank=True, max_length=20, verbose_name='Teléfono')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Fecha de creación')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Fecha de actualización')),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='usuarios_creados', to=settings.AUTH_USER_MODEL, verbose_name='Creado por')),
                ('groups', models.ManyToManyField(blank=True, help_text='The groups this user belongs to. A user will get all permissions granted to each of their groups.', related_name='user_set', related_query_name='user', to='auth.group', verbose_name='groups')),
                ('updated_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='usuarios_actualizados', to=settings.AUTH_USER_MODEL, verbose_name='Actualizado por')),
                ('user_permissions', models.ManyToManyField(blank=True, help_text='Specific permissions for this user.', related_name='user_set', related_query_name='user', to='auth.permission', verbose_name='user permissions')),
            ],
            options={
                'verbose_name': 'Usuario',
                'verbose_name_plural': 'Usuarios',
                'ordering': ['username'],
            },
            managers=[
                ('objects', django.contrib.auth.models.UserManager()),
            ],
        ),
        migrations.CreateModel(
            name='Rol',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Fecha de creación')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Fecha de actualización')),
                ('nombre', models.CharField(max_length=100, unique=True, verbose_name='Nombre del rol')),
                ('descripcion', models.TextField(blank=True, verbose_name='Descripción')),
                ('es_admin_sistema', models.BooleanField(default=False, verbose_name='Es administrador del sistema')),
                ('is_active', models.BooleanField(default=True, verbose_name='Activo')),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='%(class)s_creados', to=settings.AUTH_USER_MODEL, verbose_name='Creado por')),
                ('updated_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='%(class)s_actualizados', to=settings.AUTH_USER_MODEL, verbose_name='Actualizado por')),
            ],
            options={
                'verbose_name': 'Rol',
                'verbose_name_plural': 'Roles',
                'ordering': ['nombre'],
            },
        ),
        migrations.CreateModel(
            name='LogAuditoria',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('timestamp', models.DateTimeField(auto_now_add=True, db_index=True, verbose_name='Timestamp')),
                ('usuario_nombre', models.CharField(blank=True, max_length=255, verbose_name='Nombre del usuario')),
                ('rol', models.CharField(blank=True, max_length=255, verbose_name='Rol')),
                ('ip', models.GenericIPAddressField(blank=True, null=True, verbose_name='Dirección IP')),
                ('dispositivo', models.CharField(blank=True, max_length=255, verbose_name='Dispositivo / User-Agent')),
                ('modulo', models.CharField(blank=True, db_index=True, max_length=50, verbose_name='Módulo')),
                ('accion', models.CharField(choices=[('LOGIN', 'Inicio de sesión'), ('LOGOUT', 'Cierre de sesión'), ('LOGIN_FALLIDO', 'Intento de inicio de sesión fallido'), ('CREAR', 'Creación de registro'), ('EDITAR', 'Edición de registro'), ('ELIMINAR', 'Desactivación de registro (soft delete)'), ('APROBAR', 'Aprobación'), ('RECHAZAR', 'Rechazo'), ('FIRMAR', 'Firma digital'), ('EXPORTAR', 'Exportación de datos'), ('ACCESO_BLOQUEADO', 'Intento de acceso sin permiso'), ('API_EXTERNA', 'Llamada a API externa'), ('VER', 'Consulta de registro')], db_index=True, max_length=30, verbose_name='Acción')),
                ('entidad', models.CharField(blank=True, max_length=100, verbose_name='Entidad')),
                ('entidad_id', models.CharField(blank=True, max_length=50, verbose_name='ID de la entidad')),
                ('campo', models.CharField(blank=True, max_length=100, verbose_name='Campo')),
                ('valor_anterior', models.TextField(blank=True, null=True, verbose_name='Valor anterior')),
                ('valor_nuevo', models.TextField(blank=True, null=True, verbose_name='Valor nuevo')),
                ('referencia', models.CharField(blank=True, max_length=100, verbose_name='Referencia')),
                ('detalle', models.JSONField(blank=True, null=True, verbose_name='Detalle adicional')),
                ('usuario', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='acciones_auditoria', to=settings.AUTH_USER_MODEL, verbose_name='Usuario')),
            ],
            options={
                'verbose_name': 'Entrada de log de auditoría',
                'verbose_name_plural': 'Log de auditoría',
                'ordering': ['-timestamp'],
                'indexes': [models.Index(fields=['entidad', 'entidad_id'], name='core_logaud_entidad_a78f1b_idx'), models.Index(fields=['usuario', 'timestamp'], name='core_logaud_usuario_0123c3_idx')],
            },
        ),
        migrations.CreateModel(
            name='Permiso',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Fecha de creación')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Fecha de actualización')),
                ('modulo', models.CharField(choices=[('planeamiento', 'Planeamiento Estratégico'), ('legal', 'Gestión Legal y Cumplimiento'), ('riesgos', 'Riesgos y Oportunidades'), ('indicadores', 'Indicadores y Dashboards BI'), ('revision_direccion', 'Revisión por la Dirección'), ('documentos', 'Gestión Documental'), ('procesos', 'Gestión de Procesos'), ('hallazgos', 'Hallazgos'), ('acciones_correctivas', 'Acciones Correctivas'), ('auditorias', 'Auditorías'), ('cumplimiento', 'Cumplimiento Normativo'), ('cambios', 'Gestión de Cambios'), ('quejas', 'Quejas y Satisfacción'), ('conocimiento', 'Gestión del Conocimiento'), ('innovacion', 'Innovación I+D+i'), ('competencia_tecnica', 'Competencia Técnica'), ('equipos', 'Equipos e Instrumentos'), ('metodos', 'Métodos y Mediciones'), ('ensayos_aptitud', 'Ensayos de Aptitud'), ('trabajo_no_conforme', 'Trabajo No Conforme'), ('medio_ambiente', 'Medio Ambiente'), ('sst', 'Seguridad y Salud en el Trabajo'), ('compras', 'Compras'), ('proveedores', 'Proveedores'), ('inventarios', 'Inventarios'), ('mantenimiento', 'Mantenimiento'), ('crm', 'Comercial y CRM'), ('logistica', 'Logística'), ('ordenes_trabajo', 'Órdenes de Trabajo'), ('rrhh', 'Recursos Humanos'), ('administracion', 'Administración'), ('activos', 'Activos'), ('marketing', 'Marketing'), ('ti', 'Tecnologías de la Información'), ('usuarios', 'Gestión de Usuarios'), ('configuracion', 'Configuración del Sistema')], max_length=50, verbose_name='Módulo')),
                ('operacion', models.CharField(choices=[('leer', 'Leer'), ('crear', 'Crear'), ('editar', 'Editar'), ('aprobar', 'Aprobar'), ('eliminar', 'Eliminar')], max_length=20, verbose_name='Operación')),
                ('permitido', models.BooleanField(default=True, verbose_name='Permitido')),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='%(class)s_creados', to=settings.AUTH_USER_MODEL, verbose_name='Creado por')),
                ('updated_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='%(class)s_actualizados', to=settings.AUTH_USER_MODEL, verbose_name='Actualizado por')),
                ('rol', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='permisos', to='core.rol', verbose_name='Rol')),
            ],
            options={
                'verbose_name': 'Permiso',
                'verbose_name_plural': 'Permisos',
                'ordering': ['rol', 'modulo', 'operacion'],
                'constraints': [models.UniqueConstraint(fields=('rol', 'modulo', 'operacion'), name='unique_permiso_rol_modulo_operacion')],
            },
        ),
        migrations.CreateModel(
            name='RolUsuario',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Fecha de creación')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Fecha de actualización')),
                ('is_active', models.BooleanField(default=True, verbose_name='Activo')),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='%(class)s_creados', to=settings.AUTH_USER_MODEL, verbose_name='Creado por')),
                ('rol', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='usuarios_asignados', to='core.rol', verbose_name='Rol')),
                ('updated_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='%(class)s_actualizados', to=settings.AUTH_USER_MODEL, verbose_name='Actualizado por')),
                ('usuario', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='roles_asignados', to=settings.AUTH_USER_MODEL, verbose_name='Usuario')),
            ],
            options={
                'verbose_name': 'Rol de usuario',
                'verbose_name_plural': 'Roles de usuarios',
                'ordering': ['usuario', 'rol'],
                'constraints': [models.UniqueConstraint(fields=('usuario', 'rol'), name='unique_rol_usuario')],
            },
        ),
    ]
