# Generated by Django 5.2.15 on 2026-06-05 05:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='permiso',
            name='modulo',
            field=models.CharField(choices=[('planeamiento', 'Planeamiento Estratégico'), ('legal', 'Gestión Legal y Cumplimiento'), ('riesgos', 'Riesgos y Oportunidades'), ('indicadores', 'Indicadores y Dashboards BI'), ('revision_direccion', 'Revisión por la Dirección'), ('documentos', 'Gestión Documental'), ('procesos', 'Gestión de Procesos'), ('hallazgos', 'Hallazgos'), ('acciones_correctivas', 'Acciones Correctivas'), ('auditorias', 'Auditorías'), ('cumplimiento', 'Cumplimiento Normativo'), ('cambios', 'Gestión de Cambios'), ('quejas', 'Quejas, Reclamos y Satisfacción'), ('conocimiento', 'Gestión del Conocimiento'), ('innovacion', 'Innovación I+D+i'), ('competencia_tecnica', 'Competencia Técnica'), ('equipos', 'Equipos e Instrumentos'), ('metodos', 'Métodos y Mediciones'), ('ensayos_aptitud', 'Ensayos de Aptitud'), ('trabajo_no_conforme', 'Trabajo No Conforme'), ('medio_ambiente', 'Medio Ambiente'), ('sst', 'Seguridad y Salud en el Trabajo'), ('compras', 'Compras'), ('proveedores', 'Proveedores'), ('inventarios', 'Inventarios'), ('mantenimiento', 'Mantenimiento'), ('crm', 'Comercial y CRM'), ('logistica', 'Logística'), ('ordenes_trabajo', 'Órdenes de Trabajo'), ('rrhh', 'Recursos Humanos'), ('administracion', 'Administración'), ('activos', 'Activos'), ('marketing', 'Marketing'), ('ti', 'Tecnologías de la Información'), ('usuarios', 'Gestión de Usuarios'), ('configuracion', 'Configuración del Sistema')], max_length=50, verbose_name='Módulo'),
        ),
    ]
