# Generated by Django 5.2.15 on 2026-06-24 17:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_alter_permiso_modulo'),
    ]

    operations = [
        migrations.CreateModel(
            name='ConfiguracionSistema',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre_sistema', models.CharField(default='eSYNAPSE 360°', max_length=100, verbose_name='Nombre del sistema')),
                ('nombre_corto', models.CharField(blank=True, default='eSYNAPSE 360°', max_length=30, verbose_name='Nombre corto / sigla')),
                ('subtitulo', models.CharField(blank=True, default='Metrindust S.A.C.', max_length=150, verbose_name='Subtítulo / empresa')),
                ('logo', models.FileField(blank=True, null=True, upload_to='config/', verbose_name='Logo')),
                ('color_primario', models.CharField(blank=True, max_length=7, verbose_name='Color primario (hex)')),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Configuración del sistema',
                'verbose_name_plural': 'Configuración del sistema',
            },
        ),
        migrations.CreateModel(
            name='ModuloHabilitado',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('clave', models.CharField(max_length=40, unique=True, verbose_name='Clave')),
                ('nombre', models.CharField(max_length=100, verbose_name='Nombre')),
                ('habilitado', models.BooleanField(default=True, verbose_name='Habilitado')),
                ('dependencias', models.JSONField(blank=True, default=list, verbose_name='Depende de')),
                ('orden', models.PositiveIntegerField(default=0, verbose_name='Orden')),
            ],
            options={
                'verbose_name': 'Módulo habilitado',
                'verbose_name_plural': 'Módulos habilitados (licenciamiento)',
                'ordering': ['orden'],
            },
        ),
    ]
