# Generated by Django 5.2.15 on 2026-06-25 01:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0007_admin_sistema_mayuscula'),
    ]

    operations = [
        migrations.AddField(
            model_name='configuracionsistema',
            name='logo_empresa',
            field=models.FileField(blank=True, null=True, upload_to='config/', verbose_name='Logo de la empresa (cliente)'),
        ),
        migrations.AlterField(
            model_name='configuracionsistema',
            name='logo',
            field=models.FileField(blank=True, null=True, upload_to='config/', verbose_name='Logo del producto'),
        ),
        migrations.AlterField(
            model_name='configuracionsistema',
            name='nombre_corto',
            field=models.CharField(blank=True, default='eSYNAPSE 360°', max_length=30, verbose_name='Nombre corto / sigla'),
        ),
        migrations.AlterField(
            model_name='configuracionsistema',
            name='nombre_sistema',
            field=models.CharField(default='eSYNAPSE 360°', max_length=100, verbose_name='Nombre del sistema'),
        ),
    ]
