# Generated by Django 5.2.15 on 2026-06-25 04:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0008_configuracionsistema_logo_empresa_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='configuracionsistema',
            name='formato_hv_aprobado',
            field=models.CharField(blank=True, max_length=20, verbose_name='Sigla Aprobado'),
        ),
        migrations.AddField(
            model_name='configuracionsistema',
            name='formato_hv_codigo',
            field=models.CharField(blank=True, help_text='Código del documento de la lista maestra que define el formato; el PDF toma de su versión vigente el código, la versión y la fecha de aprobación.', max_length=30, verbose_name='Documento formato Hoja de Vida (código)'),
        ),
        migrations.AddField(
            model_name='configuracionsistema',
            name='formato_hv_elaborado',
            field=models.CharField(blank=True, max_length=20, verbose_name='Sigla Elaborado'),
        ),
        migrations.AddField(
            model_name='configuracionsistema',
            name='formato_hv_revisado',
            field=models.CharField(blank=True, max_length=20, verbose_name='Sigla Revisado'),
        ),
    ]
